### ISSUE TITLE
WebUI not functioning

### ISSUE THREAD

**Issue by Astra060** [haoheliu/AudioLDM#114]
Hello. The program works great in command-line and doesn't have any problems, however when it comes to the WebUI:
A. It can't download files, which might be the cause of my problem, I tried running with different browsers and no extension, no luck. But everything is fine with CL
B. server can't be closed with Ctrl+C it just hangs on <closing the server>
C. When generating with Web-UI this error is thrown:

```
Task exception was never retrieved
future: <Task finished name='m0wzngl3onh_0' coro=<Queue.process_events() done, defined at X:\AudioLDM-HaoHeliu\venv\Lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'm0wzngl3onh'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "X:\AudioLDM-HaoHeliu\venv\Lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu\venv\Lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu\venv\Lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'm0wzngl3onh'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by Astra060** [comment]
Install Gradio==3.36.*
