### ISSUE TITLE
Infinite audio generation

### ISSUE THREAD

**Issue by Nu70ry** [haoheliu/AudioLDM#120]
audioldm does never finish it's audio generation i don't even think it really starts it.
i waited over 2000 seconds which is over 30 minutes but nothing happens just counting seconds.

my system:
Windows 11
Python 3.8.18
Ryzen 7800X3D
RTX 4070

i did the following:
i downloaded [anaconda](https://www.anaconda.com/download)
i opened windows cmd as admin
i did conda create -n audioldm python=3.8
i did conda activate audioldm
i did cd to desktop
i did pip install audioldm (i dont have a pip3)
i did git clone https://github.com/haoheliu/AudioLDM
i did cd AudioLDM
i did python app.py (again no python3 on my system)
got [this error](https://github.com/haoheliu/AudioLDM/issues/113) and did the fix below
i did python app.py

and summited the default text and nothing more as counting seconds happen.

hope someone can tell me how to fix this.

**Comment by Nu70ry** [comment]
with commandline usage i get this error:

> RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        Unexpected key(s) in state_dict: "cond_stage_model.model.text_branch.embeddings.position_ids".

**Comment by haoheliu** [comment]
Hi please refer to this issue https://github.com/haoheliu/AudioLDM/issues/95. Maybe related

**Comment by haoheliu** [comment]
@Nu70ry Another quick fix is install laion_clap using the most up-to-date code

`pip install git+https://github.com/LAION-AI/CLAP.git`

I tried this personally and it works. Hope it helps

**Comment by Astra060** [comment]
> @Nu70ry Another quick fix is install laion_clap using the most up-to-date code
> 
> `pip install git+https://github.com/LAION-AI/CLAP.git`
> 
> I tried this personally and it works. Hope it helps

I tried your solution and issue #95, non worked. there also seems to be no errors, except when I refresh, and then press "submit" error is
```
Task exception was never retrieved
future: <Task finished name='f94ltuqx3dv_0' coro=<Queue.process_events() done, defined at X:\AudioLDM-HaoHeliu_\venv\Lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'f94ltuqx3dv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "X:\AudioLDM-HaoHeliu_\venv\Lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu_\venv\Lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu_\venv\Lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "X:\AudioLDM-HaoHeliu_\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'f94ltuqx3dv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by Astra060** [comment]
also I'm unable to stop the server, it hangs. I also have installed torch with cuda (pytorch) through pip

**Comment by Astra060** [comment]
> @Nu70ry Another quick fix is install laion_clap using the most up-to-date code
> 
> `pip install git+https://github.com/LAION-AI/CLAP.git`
> 
> I tried this personally and it works. Hope it helps

Please, specify the Gradio version used. Gradio is hot garbage, and sensitive to version changes.

**Comment by kingograder** [comment]
У меня такая же проблема. При нажатии кнопки "Исполнить" в Gradio секундомер начинает отсчет, но ничего не происходит. Так же программа не начинает потреблять ресурсы системы. 

Вывод в консоли после запуска python app.py from AudioLDM directory:
```
C:\Users\User\miniconda3\envs\audioldm\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
C:\Users\User\miniconda3\envs\audioldm\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
Running on local URL:  http://127.0.0.1:7860
```
Я уже сделал все что посоветовал haoheliu, но это безрезультатно. Очень надеюсь на вашу помощь.

**Comment by Aunmag** [comment]
Same problem
