### ISSUE TITLE
errors after trying to run app.py

### ISSUE THREAD

**Issue by Astra060** [haoheliu/AudioLDM#17]
Traceback (most recent call last):
  File "X:\AudioLDM-Neu\AudioLDM-Neu-venv\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "X:\AudioLDM-Neu\AudioLDM-Neu-venv\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "X:\AudioLDM-Neu\app.py", line 9, in <module>
    audioldm = build_model()
  File "X:\AudioLDM-Neu\audioldm\pipeline.py", line 64, in build_model
    checkpoint = torch.load(resume_from_checkpoint, map_location=device)
  File "X:\AudioLDM-Neu\AudioLDM-Neu-venv\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "X:\AudioLDM-Neu\AudioLDM-Neu-venv\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I'd appreciate any help

I have installed pytorch for cuda, and have a checkpoint in the ckpt folder, removing the checkpoint didn't change anything

**Comment by Astra060** [comment]
my bad, file was corrupted
