### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found

### ISSUE THREAD

**Issue by DrakeFruit** [haoheliu/AudioLDM#36]
when running the audio to audio script I get this error
full log:
```
Traceback (most recent call last):
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "E:\AudioLDM\AudioLDM\audioldm\__init__.py", line 3, in <module>
    from .pipeline import *
  File "E:\AudioLDM\AudioLDM\audioldm\pipeline.py", line 11, in <module>
    from audioldm.audio import wav_to_fbank, TacotronSTFT, read_wav_file
  File "E:\AudioLDM\AudioLDM\audioldm\audio\__init__.py", line 1, in <module>
    from .tools import wav_to_fbank, read_wav_file
  File "E:\AudioLDM\AudioLDM\audioldm\audio\tools.py", line 3, in <module>
    import torchaudio
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 67, in <module>
    _init_extension()
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 61, in _init_extension
    _load_lib("libtorchaudio")
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torch\_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

(audioldm) E:\AudioLDM\AudioLDM>audioldm --file_path E:\AudioLDM\AudioLDM\inputs\escapism.mp3
Traceback (most recent call last):
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "E:\AudioLDM\AudioLDM\audioldm\__init__.py", line 3, in <module>
    from .pipeline import *
  File "E:\AudioLDM\AudioLDM\audioldm\pipeline.py", line 11, in <module>
    from audioldm.audio import wav_to_fbank, TacotronSTFT, read_wav_file
  File "E:\AudioLDM\AudioLDM\audioldm\audio\__init__.py", line 1, in <module>
    from .tools import wav_to_fbank, read_wav_file
  File "E:\AudioLDM\AudioLDM\audioldm\audio\tools.py", line 3, in <module>
    import torchaudio
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 67, in <module>
    _init_extension()
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 61, in _init_extension
    _load_lib("libtorchaudio")
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torchaudio\_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\site-packages\torch\_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "C:\Users\FoxFl\anaconda3\envs\audioldm\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```

**Comment by haoheliu** [comment]
Looks like an error related to your python environment, not quite related to AudioLDM. Please check if torchaudio is properly installed. Thanks.
