### ISSUE TITLE
Cant run app.py

### ISSUE THREAD

**Issue by J3rr1ck** [haoheliu/AudioLDM#8]
hey all trying to run the app.py with the readme directions and am getting back out the following error on ubuntu 23.04
`DiffusionWrapper has 185.04 M params.
/home/jerrick/anaconda3/envs/audioldm/lib/python3.8/site-packages/torchlibrosa/stft.py:193: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
/home/jerrick/anaconda3/envs/audioldm/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    audioldm = build_model()
  File "/home/jerrick/AudioLDM/audioldm/pipeline.py", line 56, in build_model
    checkpoint = torch.load(resume_from_checkpoint, map_location=device)
  File "/home/jerrick/anaconda3/envs/audioldm/lib/python3.8/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/jerrick/anaconda3/envs/audioldm/lib/python3.8/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
`

**Comment by haoheliu** [comment]
This warning in most cases indicates the checkpoint file is corrupted, which might be because you have once interrupted the downloading of the model. Please try to remove the corrupt file by
```shell
rm ~/.cache/audioldm/audioldm-s-full.ckpt
```
and try again. Thanks.

**Comment by alexanderdutton** [comment]
Is there another way to download this file? I've tried a few times now and in each case it takes a very long time and seems to be corrupt.

Thanks for your work! Looking forward to experimenting with it.

**Comment by haoheliu** [comment]
@alexanderdutton You can also download the checkpoint here: https://zenodo.org/record/7600541#.Y_5rrezP2DU

**Comment by alexanderdutton** [comment]
Thank you!
